### ISSUE TITLE
東北大学とNICT

### ISSUE THREAD

**Issue by tomohideshibata** [himkt/awesome-bert-japanese#1]
東北大学 (a)の「サブワード分割のための語彙構築アルゴリズム」はSentencepieceだと思います。
以下のscriptで、Sentencepieceでまずvocabを学習してから、BERTのvocab.txtのフォーマットになるように変換しています。

https://github.com/cl-tohoku/bert-japanese/blob/master/build_vocab.py

東北大学 (b)の「単語 -> サブワード」は文字単位なので Character とかの方がいいのではないでしょうか。 
(「サブワード分割のための語彙構築アルゴリズム」のところ、正確にはSentencepieceの `--model_type=char` オプションで学習していますが、実質文字単位なので Character でいいと思います。)

NICT (a)の「単語 -> サブワード」はWordPieceであっていると思います。
NICT (b)が「BPEなし」モデルだと思いますが、「BPE」が人によって何を指しているのかがまちまちというのもあるのですが、ここでは「BPEなし」は「サブワードに分割せずに形態素単位」という意味なので、「単語 -> サブワード」「サブワード分割のための語彙構築アルゴリズム」ともに「--」が正しいと思います。

**Comment by himkt** [comment]
ご指摘ありがとうございます．

- e604d870 `東北大学` について修正を行いました
  - `東北大学 (a)` の語彙構築アルゴリズムを `Sentencepiece` に修正しました
  - `東北大学 (b)` の語彙構築アルゴリズムについては記載方法を迷ったのですが，`Sentencepiece (model_type=character)` とそのまま表記してみました．これに伴い，他の Sentencepiece を利用しているモデルについても model_type を記載しました．（ホットリンク:  `unigram` と記載あり，`Kikuta`: Sentencepiece のデフォルト値 (`unigram`) を利用）

- 6b85a9b `NICT` について修正を行いました
  - `NICT (a)`: `?` を削除
  - `NICT (b)`: `単語 -> サブワード` `サブワード分割のための語彙構築アルゴリズム` を削除

**Comment by tomohideshibata** [comment]
Sentencepiece (model_type=XX)と全部書いた方が正確でいいですね、ありがとうございます。
